---
title: "Project Overview"
---

## Background {#1.1Intro}

Waterbird species that overwinter in the Salish Sea have experienced significant changes in abundance in recent decades, the causes of which remain largely unresolved. Globally significant populations of sea ducks, including several vital sign indicators, are among the species experiencing declines. Long-term standardized monitoring programs have demonstrated their value for assessing broad-scale population trends of many coastal waterbirds in parts of the Salish Sea, however, a seamless approach for generating and updating transboundary trends for species and guilds has yet to be realized, nor has an approach for assessing finer-scale trends at geographic extents relevant to conservation planners been developed.

The analysis scripts developed herein closes this technical and information gap by applying spatially explicit hierarchical analytical techniques in a Bayesian framework to two parallel citizen science programs in Canada (British Columbia Coastal Waterbird Survey; BCCWS) and the U.S. (Puget Sound Seabird Survey; PSSS). Collectively, these programs have monitored overwintering waterbirds across 476 sampling locations in the Salish Sea since 2008 using a nearly identical protocol. The statistical approach we deploy takes advantage of the spatial relationships among count sites, allowing for more robust parameter estimates in places where data are sparse, and enabling trend outputs at finer spatial scales relevant to local management organizations. Further, by making these results and analytical code openly accessible, we empower resource managers with regionally tailored, regularly updated trends and annual indices of abundance, which will ultimately expedite our understanding of drivers of change and provide baselines from which to assess the outcomes of our management actions.

## Methods {#1.2Intro}

The analysis framework is spatially explicit, meaning the model borrows strength from data-rich regions to stabilize estimates in areas with sparse sampling. The user can choose from one of two spatially explicit analytical approaches. Both use spatially varying coefficients (SVCs, Gelfand et al. 2003) to account for relationships between variables (in this case, counts of birds) that are not uniform across large spatial areas. This modelling approach was first applied to continent wide bird abundance data to assess winter bird population trends using discrete aerial units (Meehan et al. 2019) and an intrinsic conditional autoregressive model (iCAR; Besag 1974). The modelling framework was later adapted (Meehan et al. 2024) to incorporate continuous space using a triangulated model mesh and stochastic partial differential equation (SPDE; Lindgren et al. 2022). The benefits of a continuous-space (SPDE) versus a discrete-space (iCAR) models are (1) finer resolution of trends, (2) a better understanding of the range of spatial correlation, and (3) a reduction in boundary effects associated with discrete-space analyses. However, many management units (such as geopolitical boundaries) are divided by discrete polygons, making the iCAR approach appropriate in many instances. We therefore develop workflows which allows for both an iCAR and SPDE SCV approach to derive estimates of annual relative abundance as well as long-term trends of coastal waterbirds in the Salish Sea.

[Details on data collection and processing can be found in the next section of this user guide](#2.1Data)

The basic statistical unit for the analysis was the maximum yearly count of each species at a survey site. We initially structured the analysis at a monthly resolution, treating monthly counts at sites as our response variable. However, model diagnostics revealed convergence failures and inflated variance components indicating poor identifiable of monthly effects. To balance temporal resolution with model stability, we aggregated counts to the maximum yearly count at each survey site. This aggregation reduced overdispersion while maintaining ecological relevance.

Species must meet the minimum data requirements in order to be included in the analysis. By default, these include (1) minimum annual abundance \>10 individuals across all sites, (2) detection in \>50% of study years (specifically \>(Y₂-Y₁)/2 years where Y₁ and Y₂ represent the study period endpoints), and (3) presence at \>10 distinct monitoring locations. [Minimum data filters can be adjusted by users before running the analysis](#3.1Analysis).

Extreme outliers in observation counts are identified using a quantile-based threshold. We calculated the outlier cutoff as three times the 99th percentile of the maximum observation count. This was done to prevent disproportionate influence from rare extreme values and to aid in model fit. Data from 2020 were also removed to due survey disruptions caused by COVID-19.

We modeled the maximum observed counts yₐₜ at site a and year t using a negative binomial distribution: yₐₜ ∼ NB(μₐₜ, ϕ) where μₐₜ = exp\[log(Dₐₜ) + fₜ + γₖ + α(sₐ)\]. The linear predictor incorporated survey duration Dₐₜ as an offset, a temporal parameter γₖ with an independent and identically distributed (IID) random effect to allow for random fluctuations in counts from year to year, and a site-level random effects fₜ with IID.

The spatial component on abundance α(sₐ) uses either the SPDE or iCAR approach. [This is user defined before running the analysis.](#3.1Analysis)

The SPDE approach uses a mesh, featuring maximum edge lengths of 25 km (inner domain) and 50 km (outer buffer), minimum vertex spacing of 2 km, and boundary constraints derived from coastline geometry. For the spatial range parameter, we set the prior such that there was a 50% probability that the spatial correlation range exceeded 20 km (i.e., P(range \> 20 km) = 0.5). For the spatial standard deviation, we set the prior so that there was a 10% probability that the marginal standard deviation exceeded 1 (i.e., P(σ \> 1) = 0.1). These priors provide weakly informative regularization, reflecting plausible spatial scales and variation while avoiding over fitting. [These priors can be adjusted by users before running an analysis](#3.1SPDE).

The iCAR approach assigned spatially structured random intercepts for each provided polygon based on the neighborhood adjacency (1=neighbour, 0 otherwise). This allowed for information on relative abundance to be shared across neighbouring polygons. Values of α(sₐ) came from a normal distribution with a mean value related to the average of adjacent cells and with a conditional variance proportional to the variance across adjacent cells and inversely proportional to the number of adjacent cells. We provide an example using the "Watersheds in the Salish Sea Bioregion" layer from the [Salish Sea Atlas Data](https://salish-sea-atlas-data-wwu.hub.arcgis.com/). Users can [upload a multipolygon spatial layer](#3.1Analysis), which covers part or all of the Salish Sea to run the analysis for the management jurisdictions of interest.

Models are fitted via integrated nested Laplace approximation (INLA) with 1,000 posterior samples drawn for uncertainty quantification. We computed annual abundance indices Ñₜ by summing exponentiated linear predictos of abundances, then derived trends using the slope and enpoint methods.

-   Slope Trend = 100 x (exp(coef(lm(log(NY) \~ Y))\[2\]) - 1)

    *The average annual rate of change across all years, estimated via ordinary least squares regression on log-transformed predicted abundances. Assumes a linear trend on a log scale. This is the output we would encourage users to select for making assessment of trends, as the end-point trend will be less stable given our model structure.*

-   Endpoint Trend = 100 × \[(Ñ_Y₂/Ñ_Y₁)\^{1/(Y₂-Y₁)} - 1\].

    *The constant annual rate that would transition NY1 to NY2 over Y2−Y1 years, assuming exponential growth. This is equivalent to the geometric mean of annual growth rates, and is standard with the Canadian Breeding Bird Survey (BBS) analysis. Because the BBS uses a GAM year effect, the smoothing of the annual indices makes the end-point approach more stable as it mitigates the sensitivity of anomalous start/end years.*

Credible intervals reflected the 2.5% and 97.5% quantiles of posterior trend estimates, with interval width calculated as their difference. The iCAR model also produces area-weighted composite indices of abundance, where [weights are assigned by the user as being equal or based on the polygon area](#3.1.1Analysis).

For analyses conducted at the guild level, we included an additional species-level random effect, also modeled with an IID, to account for unstructured heterogeneity among species.

## Results {#1.3Intro}

Select model outputs (national and international trends) are accessible through the *naturecounts* R package and will be made available through the web portal in late 2025. The outputs from this analysis will therefore provide resource managers with openly accessible annual indices of abundance for model-based management planning. User generated output will be stored in the output folder in the working directory of this project.
