project:
  type: book
  output-dir: docs

book:
  title: "Transboundary coastal waterbird trends in the Salish Sea"
  author: "Danielle Ethier"
  date: "2025-06-01"
  chapters:
    - index.qmd
    - 02_DataAccess.qmd
    - 03_Analysis.qmd
    - 99_Resources.qmd

resources:
  - Scripts/*.R
  - Data/*
  - Data/Spatial/*

bibliography: references.bib

execute:
  eval: false

format:
  html:
    toc: true
    theme: cosmo
  pdf:
    documentclass: scrreprt
