---
title: "Overview"
format: html
editor: visual
---

Waterbird species that overwinter in the Salish Sea have experienced significant changes in abundance in recent decades, the causes of which remain largely unresolved. Globally significant populations of sea ducks, including several vital sign indicators (Puget Sound Partnership, 2023), are among the species experiencing declines. Long-term standardized monitoring programs have demonstrated their value for assessing broad-scale population trends of many coastal waterbirds in parts of the Salish Sea (Anderson et al. 2009, Bower 2009, Crewe et al. 2012, Ethier et al. 2020, de Zwaan et al. 2024), however, a seamless approach for generating and updating transboundary trends for species and guilds has yet to be realized, nor has an approach for assessing finer-scale trends at geographic extents relevant to conservation planners been developed.

The analysis scripts developed herein closes this technical and information gap by applying spatially explicit hierarchical analytical techniques in a Bayesian framework to two parallel citizen science programs in Canada (British Columbia Coastal Waterbird Survey; BCCWS) and the U.S. (Puget Sound Seabird Survey; PSSS). Collectively, these programs have monitored overwintering waterbirds across 476 sampling locations in the Salish Sea since 2008 using a nearly identical protocol. The statistical approach we deploy takes advantage of the spatial relationships among count sites, allowing for more robust parameter estimates in places where data are sparse, and enabling trend outputs at finer spatial scales relevant to local management organizations. Further, by making these results and analytical code openly accessible, we empower resource managers with regionally tailored, regularly updated trends and annual indices of abundance, which will ultimately expedite our understanding of drivers of change and provide baselines from which to assess the outcomes of our management actions.

## Goals {#1.1Intro}

The goals of this user guide is to empower resource managers to leverage standardized citizen-science monitoring data, collected by the BCCWS and PSSS, to (1) obtain scientifically credible measures of abundance trends of coastal waterbirds in the transboundary waters of the Salish Seas at scales appropriate for resource management, (2) identify priority species for conservation, and (3) provide resource managers with openly accessible annual indices of abundance for model-based management planning. In turn, these modelling outputs can be used to assess environmental and human-induced mechanisms of waterbird changes and provide a foundation from which to tease apart whether local population fluctuations are a result of true changing abundance or shifts in species distributions over time.

## Methods {#1.2Intro}

The user can choose from one of two spatially explicit analytical approaches. Both use spatially varying coefficients (SVCs, Gelfand et al. 2003) to account for relationships between variables that are not uniform across large spatial areas. This modelling approach was first applied to continent wide bird abundance data to assess winter bird population trends using discrete aerial units (Meehan et al. 2019) and an intrinsic conditional autoregressive model (iCAR; Besag 1974). The modelling framework was later adapted (Meehan et al. 2024) to incorporate continuous space using a triangulated model mesh and stochastic partial differential equation (SPDE; Lindgren et al. 2022). The benefits of a continuous-space (SPDE) versus a discrete-space (iCAR) models are (1) finer resolution of trends, (2) a better understanding of the range of spatial correlation, and (3) a reduction in boundary effects associated with discrete-space analyses. However, many management units (such as geopolitical boundaries) are divided by discrete polygons, making the iCAR approach appropriate in many instances. We therefore develop workflows which allows for both an iCAR and SPDE SCV approach to derive estimates of annual relative abundance as well as long-term trends of coastal waterbirds in the Salish Sea.

[Details on data collection and processing can be found in the next section of this user guide](#2.1Data)

The basic statistical unit for the analysis was the maximum yearly count of each species at a survey site. We initially structured the analysis at a monthly resolution, treating monthly counts at site as our response variable. However, model diagnostics revealed convergence failures and inflated variance components indicating poor identifiable of monthly effects. To balance temporal resolution with model stability, we aggregated counts to the maximum yearly count at each survey site. This aggregation reduced overdispersion while maintaining ecological relevance.

Species must meet the minimum data filters in order to be included in the analysis: (1) minimum annual abundance \>10 individuals across all sites, (2) detection in \>50% of study years (specifically \>(Y₂-Y₁)/2 years where Y₁ and Y₂ represent the study period endpoints), and (3) presence at \>10 distinct monitoring locations. [Species selection and data filters can be adjusted by users before running an analysis](#3.1Analysis).

Extreme outliers in observation counts are identified using a quantile-based threshold. We calculated the outlier cutoff as three times the 99th percentile of the maximum observation count. This was done to prevent disproportionate influence from rare extreme values and to aid in model fit. Data from 2020 were also removed to due survey disruptions caused by COVID-19.

We modeled the maximum observed counts yₐₜ at site a and year t using a negative binomial distribution: yₐₜ ∼ NB(μₐₜ, ϕ) where μₐₜ = exp\[log(Dₐₜ) + β₀ + fₜ + γₖ + α(sₐ)\]. The linear predictor incorporated survey duration Dₐₜ as an offset, a global intercept β₀, a temporal parameter γₖ with an independent and identically distributed (IID) random effect to allow for random fluctuations in counts from year to year, and a site-level random effects fₜ with IID.

The spatial component on abundance α(sₐ) uses either the SPDE or iCAR approach. [This is user defined before running the analysis.](#3.1Analysis)

The SPDE approach with a mesh, featuring maximum edge lengths of 25 km (inner domain) and 50 km (outer buffer), minimum vertex spacing of 2 km, and boundary constraints derived from coastline geometry. For the spatial range parameter, we set the prior such that there was a 50% probability that the spatial correlation range exceeded 20 km (i.e., P(range \> 20 km) = 0.5). For the spatial standard deviation, we set the prior so that there was a 10% probability that the marginal standard deviation exceeded 1 (i.e., P(σ \> 1) = 0.1). These priors provide weakly informative regularization, reflecting plausible spatial scales and variation while avoiding overfitting. [These priors can be adjusted by users before running an analysis](#3.1SPDE).

The iCAR spatially structured random intercepts for each provided polygon, modeled using a Besag intrinsic conditional autoregressive (ICAR) prior based on the neighborhood structure. We provide an example using the "Watersheds in the Salish Sea Bioregion" layer from the [Salish Sea Atlas Data](https://salish-sea-atlas-data-wwu.hub.arcgis.com/) as an example. The user can upload a multipolygon feature which covers part or all of the Salish Sea to run the analysis for their management jurisdiction.

Models were fitted via integrated nested Laplace approximation (INLA) with 1,000 posterior samples drawn for uncertainty quantification. We computed annual abundance indices Ñₜ by summing exponentiated linear predictors across all sites, then derived trends using the endpoint and slope methods.

-   Endpoint Trend = 100 × \[(Ñ_Y₂/Ñ_Y₁)\^{1/(Y₂-Y₁)} - 1\].

-   Slope Trend = 100 x (exp(coef(lm(log(NY) \~ Y))\[2\]) - 1)

Credible intervals reflected the 2.5% and 97.5% quantiles of posterior trend estimates, with interval width calculated as their difference.

For analyses conducted at the guild level, we included an additional species-level random effect, also modeled with an IID, to account for unstructured heterogeneity among species within each guild.

## Results {#1.3Intro}

All model outputs are displayed on the NatureCounts web portal and are accessible through the *naturecounts* R package. The outputs from this analysis will therefore provide resource managers with openly accessible annual indices of abundance for model-based management planning.

## Using this Technical Guide

In this technical guide we detailing the analytical methods used to calculate broad- and fine-scale trends and annual indices of abundance for all species regularly monitored by the BCCWS and PSSS. Specifically, this guide will provide step-by-step instructions on (1) data access, (2) data wrangling and processing, (3) setting up the analysis for various spatial scales (continuous and discrete space), and (4) running the analysis and generating output tables and maps. This guide assumes that you have a basic understanding of R. We recommend that you become familiar with ['R for Data Science'](http://r4ds.had.co.nz/) by Garrett Grolemund and Hadley Wickham, which covers how to import, visualize, and summarize data in R using the [tidyverse](https://www.tidyverse.org/) collection of R packages.

R scripts and code resources associated with this project are available on the [Birds Canada GitHub](https://github.com/BirdsCanada) page and in the [Resource](#9.9BirdsCan) section of this guide.

## Acknowledgement {#1.4Intro}

This project was financially supported by the SeaDoc Society, a program of the Karen C. Drayer Wildlife Health Center, School of Veterinary Medicine, University of California, Davis.
